name: state_notifier_test_app
description: A test app for StateNotifier.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI
  lottie:
  cupertino_icons: ^0.1.2

  # Architecture
  freezed_annotation:
  state_notifier: ^0.4.0
  flutter_state_notifier: ^0.4.0
  provider: ^4.1.0-dev

  # Firebase
  firebase_core:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true
  assets:
    - images/
    - lottie/