name: state_notifier_test_app
description: A test app for StateNotifier.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  freezed_annotation:
  flutter_state_notifier:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true